name: Deploy to AKS from ACR

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: test0107.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -t test0107.azurecr.io/asg:${{ github.sha }} .
        docker push test0107.azurecr.io/asg:${{ github.sha }}
    - name: Pull Docker image from ACR
      run: |
        docker pull test0107.azurecr.io/asg:${{ github.sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set kubectl context
      uses: azure/aks-set-context@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: <cluster-name>
          resource-group: <resource-group-name>

    - name: Apply Kubernetes Secret
      run: |
          kubectl apply -f path/to/acr-secret.yaml

    - name: Deploy to AKS
      run: |
          kubectl apply -f path/to/deployment.yaml
